


/* Generated by glib-mkenums. Do not edit */

#include "mega-enum-types.h"

#include "mega-aes-key.h" 
#include "mega-rsa-key.h" 
#include "mega-chunked-cbc-mac.h" 
#include "mega-http-client.h" 
#include "mega-http-io-stream.h" 
#include "mega-http-input-stream.h" 
#include "mega-http-output-stream.h" 
#include "mega-aes-ctr-encryptor.h" 
#include "utils.h" 
#include "megatypes.h" 
#include "mega.h"

GType
mega_http_client_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { MEGA_HTTP_CLIENT_ERROR_CONNECTION_BROKEN, "MEGA_HTTP_CLIENT_ERROR_CONNECTION_BROKEN", "connection-broken" },
        { MEGA_HTTP_CLIENT_ERROR_SERVER_BUSY, "MEGA_HTTP_CLIENT_ERROR_SERVER_BUSY", "server-busy" },
        { MEGA_HTTP_CLIENT_ERROR_OTHER, "MEGA_HTTP_CLIENT_ERROR_OTHER", "other" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("MegaHttpClientError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
mega_hex_format_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { MEGA_HEX_FORMAT_PACKED, "MEGA_HEX_FORMAT_PACKED", "packed" },
        { MEGA_HEX_FORMAT_C, "MEGA_HEX_FORMAT_C", "c" },
        { MEGA_HEX_FORMAT_STRING, "MEGA_HEX_FORMAT_STRING", "string" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("MegaHexFormat"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}



